# Generated by Django 2.2.6 on 2021-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToolsModels',
            new_name='ToolsModel',
        ),
    ]
