# Generated by Django 2.2.6 on 2021-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_api', '0002_auto_20210428_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitymodel',
            name='CHOICES',
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='entity_type',
            field=models.CharField(choices=[('HL', 'Hospital'), ('PN', 'Person')], default='PN', max_length=3),
        ),
        migrations.AlterField(
            model_name='sosmodel',
            name='sos_state',
            field=models.CharField(choices=[('AE', 'Active'), ('IE', 'Inactive')], default='IE', max_length=3),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='tool_state',
            field=models.CharField(choices=[('AE', 'Active'), ('IE', 'Inactive')], default='IE', max_length=3),
        ),
    ]
